config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index,:show, :new, :create] do
    resources :baskets, only: [:new, :create]
  end
  resources :players, only: [:index, :show, :new]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :venue
  has_many :baskets
  has_many :players, through: :baskets

  accepts_nested_attributes_for :venue
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :baskets
  has_many :games, through: :baskets
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)
    @game.save
    redirect_to @game
  end

private

  def game_params
    params.require(:game).permit(:date,:venue_id)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    player = Player.create(player_params)
    redirect_to @player
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/games/index.html.erb
<h2>Welcome to Sixer's Game Page</h2>
<h3>Choose a Game Date:</h3>

<ul>
  <% @games.each do |game| %>
    <li>
     <td><%= game.date %></td>
    <td><%= game.venue_id %></td>
      <%= link_to @game.date, games_path(@game) %>
    </li>
    <br>
  <% end %>
</ul>

app/views/games/new.html.erb
<%= form_for @game do |f|%>
    <%= f.label :date %><br>
    <%= f.text_field :date %>

    <%= f.label :venue %><br>
    <%= f.text_field :venue %>

    <%= f.submit %>
<% end %>

app/views/games/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @game.venue %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSixersRoster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<h1>Sixer Player's Roster</h1>
<h2>Choose a Player to See Their Stats:</h2>

  <% @players.each do |player| %>
    <li>
      <%= link_to player.name, player_path(player) %>

    <br>
  <% end %>
</ul>

app/views/players/new.html.erb
<%= form_for [@game, @player] do |f|%>
    <%= f.label :name %><br>
    <%= f.text_field :name %>

    <%= f.label :number %><br>
    <%= f.text_field :number %>

    <%= f.submit %>
<% end %>

app/views/players/show.html.erb
Player Name: <%= @player.name %>
Player Number: <%= @player.number %>

app/views/venues/index.html.erb
<h1>Venues:</h1>
<%= link_to "Games", controller: "games" %>